# For training & scheduling
epochs: 100
lr: 0.4
tuned: True
weight_decay: 0.000005
optimizer: Adam

# For dataloader
data_path: data/
dataset: pubmed   # choices: cora, citeseer, pubmed, reddit
test: True        # reddit
inductive: True   # reddit

# For pre-processed feature
norm_type: AugNormAdj
gamma: 1.0

# For loading model
alpha: 0.1
degree: 2
